apm-server:
  host: 0.0.0.0:8200
  rum:
    enabled: true

output:
  elasticsearch:
    hosts: ["http://elasticsearch01:9200","http://elasticsearch02:9200","http://elasticsearch03:9200"]
    username: $ELASTICSEARCH_USERNAME
    password: $ELASTICSEARCH_PASSWORD

# output.elasticsearch.index: "application-monitoring-%{[agent.version]}-%{+yyyy.MM.dd}"
# setup.template.name: "apm"
# setup.template.pattern: "apm-*"

setup.kibana.host: http://kibana:5601
setup.kibana.username: $ELASTICSEARCH_USERNAME
setup.kibana.password: $ELASTICSEARCH_PASSWORD

xpack.monitoring.enabled: true
