heartbeat.monitors:
- type: http
  schedule: '@every 10s'
  urls:
    - http://elasticsearch01:9200
    - http://elasticsearch02:9200
    - http://elasticsearch03:9200
    - http://kibana:5601

  check.request:
    method: GET
    headers:
        'Content-Type': 'application/json' 
  check.response:
       status: 200
       

output.elasticsearch:
  hosts: ["http://elasticsearch01:9200","http://elasticsearch02:9200","http://elasticsearch03:9200"]
  username: $ELASTICSEARCH_USERNAME
  password: $ELASTICSEARCH_PASSWORD

setup.kibana:
  host: "kibana:5601"
  username: $ELASTICSEARCH_USERNAME
  password: $ELASTICSEARCH_PASSWORD