heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch01:9200
    - http://elasticsearch02:9200
    - http://elasticsearch03:9200
    - http://logstash:5000
    - http://apm-server:8200
    - http://192.168.0.39:4200
    - http://192.168.0.39:8080

  check.request:
    method: GET
    headers:
        'Content-Type': 'application/json' 
  check.response:
       status: 200


output.elasticsearch:
  hosts: ["http://elasticsearch01:9200","http://elasticsearch02:9200","http://elasticsearch03:9200"]
  username: $ELASTICSEARCH_USERNAME
  password: $ELASTICSEARCH_PASSWORD

setup.kibana:
  host: http//kibana:5601
  username: $ELASTICSEARCH_USERNAME
  password: $ELASTICSEARCH_PASSWORD